site_name: BeyondATC Help Center
site_url: https://wiki.beyondatc.net
copyright: Created with 💜 by Dialex
theme:
  name: material
  custom_dir: overrides
  font: 
    text: Albert Sans
  features:
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - navigation.instant
  - search.highlight
  - search.share
  - search.suggest
  - toc.integrate
  - instant

  palette:
    # Dark mode
    - scheme: batc-dark
      accent: deep purple

  logo: assets/logo.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  admonition: {}
  pymdownx.details: {}
  pymdownx.superfences: {}
  def_list: {}
  attr_list: {}
  md_in_html: {}
  tables: {}
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
nav:
  - Home: 'index.md'
  - Onboarding:
    - 'Overview': 'onboarding/overview.md'
    - 'Features': 'onboarding/features.md'
    - 'Pricing': 'onboarding/pricing.md'
    - 'Getting started': 'onboarding/getting-started.md'
  - Beginner Guide:
    - 'Overview': 'beginner-guide/overview.md'
    - 'Preflight': 'beginner-guide/preflight.md'
    - 'Departure': 'beginner-guide/departure.md'
    - 'Cruise': 'beginner-guide/cruise.md'
    - 'Arrival': 'beginner-guide/arrival.md'
  - Knowledge Base:
    - 'knowledge-base/index.md'
  - Resources:
    - 'Resources': 'resources/resources.md'
  - Support:
    - 'Bug reporting': 'support/bug-reporting.md'
    - 'FAQ': 'support/faq.md'
    - 'Common issues':
      - "BeyondATC update failed": 'support/common-issues/update.md'
      - "Can't connect to the simulator": 'support/common-issues/simconnect.md'
      - "Change the output device": 'support/common-issues/output.md'
      - "No AI traffic": 'support/common-issues/notraffic.md'
      - "Simbrief cannot be reached": 'support/common-issues/simbrief.md'

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/beyondatc